-- QY Workforce: consent-state and worker matching hardening.
-- Consent is an append-only decision history. The latest decision for a purpose,
-- rather than any historic grant, is authoritative for readiness and identity use.

alter table public.worker_consents
  drop constraint if exists worker_consents_withdrawal_state_check;
alter table public.worker_consents
  add constraint worker_consents_withdrawal_state_check
  check (
    (granted = true and withdrawn_at is null)
    or (granted = false and withdrawn_at is not null)
  ) not valid;

-- A monotonic server-issued sequence resolves the otherwise rare case of two
-- decisions receiving the same timestamp without trusting a client timestamp.
alter table public.worker_consents
  add column if not exists decision_sequence bigint generated by default as identity;

create index if not exists worker_consents_current_decision_idx
  on public.worker_consents(worker_id, purpose, recorded_at desc, decision_sequence desc);

-- No client may manufacture, backdate or alter a consent record directly. The
-- onboarding RPC retains its server-side insert path; subsequent changes use the
-- narrow RPC below so withdrawal is immediate and auditable.
drop policy if exists "workers create own consents" on public.worker_consents;
revoke insert, update, delete on public.worker_consents from anon, authenticated;

create or replace function public.worker_has_active_consent(
  p_worker_id uuid,
  p_purpose text
)
returns boolean
language sql
stable
security definer
set search_path = public
as $$
  select coalesce((
    select c.granted = true and c.withdrawn_at is null
    from public.worker_consents c
    where c.worker_id = p_worker_id
      and c.purpose = p_purpose
    order by c.recorded_at desc, c.decision_sequence desc
    limit 1
  ), false);
$$;

revoke all on function public.worker_has_active_consent(uuid,text) from public;

create or replace function public.set_worker_operational_consent(
  p_purpose text,
  p_granted boolean,
  p_policy_version text
)
returns uuid
language plpgsql
security definer
set search_path = public
as $$
declare
  v_id uuid;
  v_purpose text := lower(trim(coalesce(p_purpose,'')));
  v_version text := nullif(trim(p_policy_version),'');
begin
  if auth.uid() is null then raise exception 'authentication required'; end if;
  if not exists (select 1 from public.worker_profiles where user_id = auth.uid()) then
    raise exception 'worker profile required';
  end if;
  if p_granted is null then raise exception 'consent decision required'; end if;
  if v_purpose not in ('identity_verification','work_eligibility','location_clocking','analytics') then
    raise exception 'unsupported operational consent purpose';
  end if;
  if v_version is null or char_length(v_version) not between 4 and 120 then
    raise exception 'policy version must be between 4 and 120 characters';
  end if;

  insert into public.worker_consents(worker_id,purpose,policy_version,granted,withdrawn_at,source)
  values(auth.uid(),v_purpose,v_version,p_granted,
         case when p_granted then null else now() end,'worker_app')
  returning id into v_id;

  insert into public.audit_events(actor_id,action,entity_type,entity_id,metadata)
  values(auth.uid(),'worker.operational_consent_recorded','worker_consent',v_id,
    jsonb_build_object('purpose',v_purpose,'granted',p_granted,'policy_version',v_version));
  return v_id;
end;
$$;

revoke all on function public.set_worker_operational_consent(text,boolean,text) from public;
grant execute on function public.set_worker_operational_consent(text,boolean,text) to authenticated;

create or replace function public.worker_has_deployment_prerequisites(p_worker_id uuid)
returns boolean
language sql
stable
security definer
set search_path = public
as $$
  select coalesce((
    select wp.identity_verified
      and wp.residency_verified
      and wp.work_eligibility = 'eligible'
      and wp.status not in ('suspended','rejected')
      and exists (
        select 1 from public.worker_roles wr join public.roles r on r.id=wr.role_id
        where wr.worker_id=wp.user_id and wr.approved and r.active
      )
      and not exists (
        select 1 from public.worker_vetting wv
        where wv.worker_id=wp.user_id and wv.status in ('pending','failed','manual_review')
      )
      and not exists (
        select 1 from public.training_modules tm
        where tm.active and (tm.role_id is null or exists (
          select 1 from public.worker_roles wr
          where wr.worker_id=wp.user_id and wr.role_id=tm.role_id and wr.approved
        )) and not exists (
          select 1 from public.worker_training wt
          where wt.worker_id=wp.user_id and wt.module_id=tm.id and wt.status='passed'
            and (wt.expires_at is null or wt.expires_at > now())
        )
      )
      and public.worker_has_active_consent(wp.user_id,'identity_verification')
      and public.worker_has_active_consent(wp.user_id,'work_eligibility')
      and public.worker_has_active_consent(wp.user_id,'location_clocking')
    from public.worker_profiles wp where wp.user_id=p_worker_id
  ),false);
$$;

revoke all on function public.worker_has_deployment_prerequisites(uuid) from public;

create or replace function public.get_worker_readiness()
returns table (
  worker_status public.worker_status, identity_verified boolean, residency_verified boolean,
  work_eligibility public.eligibility_status, approved_roles integer, verified_skills integer,
  outstanding_training integer, failed_vetting integer, required_consents_complete boolean,
  deployable boolean
)
language sql stable security definer set search_path=public as $$
  with me as (select wp.* from public.worker_profiles wp where wp.user_id=auth.uid()),
  role_count as (select count(*)::int n from public.worker_roles wr join public.roles r on r.id=wr.role_id where wr.worker_id=auth.uid() and wr.approved and r.active),
  skill_count as (select count(*)::int n from public.worker_skills ws where ws.worker_id=auth.uid() and ws.verified),
  training_count as (select count(*)::int n from public.training_modules tm where tm.active and (tm.role_id is null or exists (select 1 from public.worker_roles wr where wr.worker_id=auth.uid() and wr.role_id=tm.role_id and wr.approved)) and not exists (select 1 from public.worker_training wt where wt.worker_id=auth.uid() and wt.module_id=tm.id and wt.status='passed' and (wt.expires_at is null or wt.expires_at>now()))),
  vetting_count as (select count(*)::int n from public.worker_vetting wv where wv.worker_id=auth.uid() and wv.status in ('failed','manual_review')),
  consent_state as (select public.worker_has_active_consent(auth.uid(),'identity_verification') and public.worker_has_active_consent(auth.uid(),'work_eligibility') and public.worker_has_active_consent(auth.uid(),'location_clocking') ok)
  select me.status,me.identity_verified,me.residency_verified,me.work_eligibility,role_count.n,skill_count.n,training_count.n,vetting_count.n,consent_state.ok,public.worker_is_deployable(auth.uid())
  from me,role_count,skill_count,training_count,vetting_count,consent_state;
$$;
revoke all on function public.get_worker_readiness() from public;
grant execute on function public.get_worker_readiness() to authenticated;

-- Keep the feed aligned with acceptance: prerequisites are live, but an explicit
-- Ops deployable status remains the final independent authorization gate.
create or replace function public.get_available_shifts()
returns table (shift_id uuid, role_name text, client_name text, site_name text, starts_at timestamptz, ends_at timestamptz, worker_rate numeric, requirements jsonb, available_slots integer)
language plpgsql security definer stable set search_path=public as $$
begin
  if auth.uid() is null then raise exception 'authentication required'; end if;
  if not public.worker_has_deployment_prerequisites(auth.uid()) then return; end if;
  if not public.worker_is_deployable(auth.uid()) then return; end if;
  return query
  select sh.id,r.name,c.name,s.name,sh.starts_at,sh.ends_at,sh.worker_rate,coalesce(sh.requirements,'{}'::jsonb),greatest(sh.headcount-(select count(*)::integer from public.shift_assignments a where a.shift_id=sh.id and a.cancelled_at is null),0)
  from public.shifts sh join public.roles r on r.id=sh.role_id join public.sites s on s.id=sh.site_id join public.clients c on c.id=s.client_id
  where sh.status='open' and sh.starts_at>now() and r.active and s.active and c.active
    and exists(select 1 from public.worker_roles wr where wr.worker_id=auth.uid() and wr.role_id=sh.role_id and wr.approved)
    and not exists(select 1 from public.shift_assignments mine where mine.shift_id=sh.id and mine.worker_id=auth.uid() and mine.cancelled_at is null)
    and not exists(select 1 from public.shift_assignments mine join public.shifts existing on existing.id=mine.shift_id where mine.worker_id=auth.uid() and mine.cancelled_at is null and existing.status<>'cancelled' and existing.starts_at<sh.ends_at and existing.ends_at>sh.starts_at)
    and (select count(*) from public.shift_assignments active where active.shift_id=sh.id and active.cancelled_at is null)<sh.headcount
  order by sh.starts_at asc limit 100;
end;
$$;
revoke all on function public.get_available_shifts() from public;
grant execute on function public.get_available_shifts() to authenticated;

create or replace function public.start_identity_session(
  p_provider text default 'mock', p_environment text default 'mock', p_state_hash text default null,
  p_nonce_hash text default null, p_requested_scopes text[] default array['openid']::text[]
) returns uuid language plpgsql security definer set search_path=public as $$
declare v_id uuid; v_scopes text[];
begin
  if auth.uid() is null then raise exception 'authentication required'; end if;
  if not exists(select 1 from public.worker_profiles where user_id=auth.uid()) then raise exception 'worker profile required'; end if;
  if p_provider not in ('mock','singpass_myinfo') then raise exception 'unsupported identity provider'; end if;
  if p_environment not in ('mock','staging') then raise exception 'production identity flow not enabled'; end if;
  if nullif(trim(p_state_hash),'') is null or char_length(trim(p_state_hash)) not between 32 and 256 then raise exception 'valid state hash required'; end if;
  if nullif(trim(p_nonce_hash),'') is null or char_length(trim(p_nonce_hash)) not between 32 and 256 then raise exception 'valid nonce hash required'; end if;
  select coalesce(array_agg(scope order by scope),'{}'::text[]) into v_scopes from (select distinct lower(trim(scope)) scope from unnest(coalesce(p_requested_scopes,'{}'::text[])) u(scope) where nullif(trim(scope),'') is not null) requested;
  if coalesce(array_length(v_scopes,1),0)<>1 or v_scopes[1]<>'openid' then raise exception 'only the openid scope is permitted for mock/staging identity sessions'; end if;
  if not public.worker_has_active_consent(auth.uid(),'identity_verification') then raise exception 'identity verification consent required'; end if;
  update public.identity_provider_sessions set status='expired' where worker_id=auth.uid() and provider=p_provider and environment=p_environment and status in ('initiated','callback_received') and expires_at<=now();
  if exists(select 1 from public.identity_provider_sessions where worker_id=auth.uid() and provider=p_provider and environment=p_environment and status in ('initiated','callback_received') and expires_at>now()) then raise exception 'identity session already active'; end if;
  insert into public.identity_provider_sessions(worker_id,provider,environment,state_hash,nonce_hash,requested_scopes,expires_at) values(auth.uid(),p_provider,p_environment,trim(p_state_hash),trim(p_nonce_hash),v_scopes,now()+interval '10 minutes') returning id into v_id;
  insert into public.audit_events(actor_id,action,entity_type,entity_id,metadata) values(auth.uid(),'identity_session.started','identity_provider_session',v_id,jsonb_build_object('provider',p_provider,'environment',p_environment,'scope_count',1));
  return v_id;
end;
$$;
revoke all on function public.start_identity_session(text,text,text,text,text[]) from public;
grant execute on function public.start_identity_session(text,text,text,text,text[]) to authenticated;

comment on function public.worker_has_active_consent(uuid,text) is 'Authoritative latest-decision consent check. Historic grants never override a later withdrawal.';
